### ISSUE TITLE
RTF clarification

### ISSUE THREAD

**Issue by AdolfVonKleist** [Picovoice/wake-word-benchmark#3]
Could you clarify the RTF numbers in your table?  You link to the normal RTF definition, and indicate that the RTF for Porcupine is lower than other options, but the RTF for Pocketsphinx is written `3.15(xRT)` and PorcupineTiny at `29.28(xRT)`, nearly 10x slower.  I suppose all of the options are `<1xRT`, but this is not so clear from the description; or maybe I am reading it wrong.  Thanks!

**Comment by kenarsa** [comment]
You are absolutely correct. The results are shown as the inverse. This [commit](https://github.com/Picovoice/wakeword-benchmark/commit/a86b666475b072fac4edfa8fcd42b6e93dce3ea2) fixes the issue.

Thank you for finding and reporting the issue. Much appreciate it. I am closing the issue. But feel free to re-open if you see any discrepancies.
