### ISSUE TITLE
git clone permission issue

### ISSUE THREAD

**Issue by maulikmadhavi** [Picovoice/wake-word-benchmark#5]
Hi I cannot clone this repo by running
`git clone --recurse-submodules git@github.com:Picovoice/wakeword-benchmark.git`

It  generates 

> Cloning into 'wakeword-benchmark'...
> The authenticity of host 'github.com (13.229.188.59)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added 'github.com,13.229.188.59' (RSA) to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.

Thanks
Maulik

**Comment by kenarsa** [comment]
do you have SSH setup? maybe google that.

**Comment by maulikmadhavi** [comment]
Thanks, it worked!

**Comment by csukuangfj** [comment]
@kenarsa 

it would be better to replace it with

git clone --recurse-submodules https://github.com/Picovoice/wakeword-benchmark.git

so that it can be easily reproduced even for newbies.

(the submodules should also be replaced with https)
