### ISSUE TITLE
unnecessary recomputaion of `_pcm_energy(speech)`

### ISSUE THREAD

**Issue by csukuangfj** [Picovoice/wake-word-benchmark#6]
See the code
https://github.com/Picovoice/wakeword-benchmark/blob/1a6745de51577f646cfb46d061b85415d5216425/mixer.py#L36-L43

`speech_energy` is computed at
https://github.com/Picovoice/wakeword-benchmark/blob/1a6745de51577f646cfb46d061b85415d5216425/mixer.py#L39

Therefore, line
https://github.com/Picovoice/wakeword-benchmark/blob/1a6745de51577f646cfb46d061b85415d5216425/mixer.py#L43
can use `speech_energy` directly instead of computing it again.

**Comment by kenarsa** [comment]
Cool! Can you please submit a PR and I will merge it in. Thanks.
